show databases;
use studentdb;
create table emp (Empno int(10) primary key,ename varchar(30), job char(10), deptno int(10));
desc emp;
alter table emp add(Phone int (10));
alter table emp add column (Phone2 int (10));
alter table emp drop column Phone;
alter table emp modify column phone2 int(8) not null;
alter table emp drop phone2;
drop table emp;
create table emp (EMPNO INT PRIMARY KEY,ENAME VARCHAR(20),JOB VARCHAR(20),MGR INT(4),DEPTNO INT(3),SAL DOUBLE(7,2));
alter table emp modify column job VARCHar(20) not null;
alter table emp add column(dob date,comm int(10));
insert into emp (EMPNO,ENAME,JOB,MGR,DOB,SAL,COMM,DEPTNO) values (7369,'SMITH','CLERK',7566,'17-DEC-80',800,0,20);
select * from emp;
select ename as name from emp where deptno in (select deptno from emp where empno in (7369,7499));
select ename as NAME , sal AS FEES from emp order by sal asc;
SELECT DISTINCT DEPTNO FROM EMP;
SELECT * FROM EMP;
insert into emp (EMPNO,ENAME,JOB,MGR,DOB,SAL,COMM,DEPTNO) values (7611,'SCOTT','HOD',7839,'1976-05-20',3000,0,10) (7839,'CLARK','CEO',NULL,'1972-05-20',9900,0,10);
select distinct deptno from emp order by deptno desc;
select ename as name , job as department from emp;
select ename from emp where mgr is null and job = 'ceo';
select max(sal) as tot_sal from emp;
select ename as name from emp where ename like '%n' or ename like '%t';
select count(distinct job) as no_of_jobs from emp;
select sum(sal) as sal,job from emp group by job;
select sum(sal),DEPTNO from emp where sal > 1200  group by deptno ;
insert into emp (EMPNO,ENAME,JOB,MGR,DOB,SAL,COMM,DEPTNO) values (7566,'JONES','MANAGER',7839,'1976-05-01',5975,500,20);
insert into emp (EMPNO,ENAME,JOB,MGR,DOB,SAL,COMM,DEPTNO) values (7599,'ALLEY','SALESMAN',7698,'1981-02-02',1600,300,30),(7421,'DRANK','CLERK',7698,'1982-01-22',1250,500,30);
select ename,empno from emp ;
select max(sal),deptno from emp group by DEPTNO asc; 
select ename from emp where ename like 'b%' or ename like'j%';
select ename,sal,(0.15*sal)+sal as new_sal from emp;
select count(*),deptno,job from emp group by deptno;
create table dept (DEPTNO INT(20),DNAME VARCHAR(20),LOC VARCHAR(20));
INSERT INTO DEPT (DEPTNO,DNAME,LOC) VALUES (10,'MANAGEMENT','MAIN BLOCK'),(20,'DEVELOPMENT','MANUFACTURING UNIT'),(30,'MAINTAINANCE','MAIN BLOCK'),(40,'TRANSPORT','ADMIN BLOCK'),(50,'SALES','HEAD OFFICE');
select dname,deptno from dept where deptno in (select deptno from emp);
select dname,dept.deptno,ename,empno,job,max(sal) as maxsal from emp,dept group by emp.deptno;
select * from dept;
truncate table dept;
INSERT INTO DEPT VALUES(10,'MANAGEMENT','MAIN BLOCK'),
 (20,'DEVELOPMENT','MANUFACTURING UNIT'),
 (30,'MAINTAINANCE','MAIN BLOCK'),
 (40,'TRANSPORT','ADMIN BLOCK'), (50,'SALES','HEAD OFFICE');
SELECT * FROM DUAL;
DELETE FROM EMP WHERE EMPNO in (7039);
Select * from emp order by sal asc;
SELECT ENAME , SAL, SAL*1.15 FROM EMP ;
SELECT ENAME FROM EMP WHERE  ENAME LIKE'B%' OR ENAME LIKE'C%';
SELECT dept.deptno,ename,dname FROM EMP,dept where emp.deptno=dept.deptno ;
SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;
SELECT * FROM EMP CROSS JOIN DEPT;
select deptno from dept where DNAME in ('MAINTAINANCE','DEVELOPMENT');
select ename from emp;
select ename,(select dname from dept where dept.deptno=emp.deptno) as deptname from emp where emp.deptno in (select deptno from dept where DNAME in ('MAINTAINANCE','DEVELOPMENT'));
SELECT COUNT(*),DNAME FROM EMP ,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO GROUP BY DNAME;
SELECT ENAME, DNAME FROM EMP,DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO AND DEPT.DNAME='MAINTAINANCE' OR EMP.DEPTNO=DEPT.DEPTNO AND DEPT.DNAME='DEVELOPMENT';
select ename,sal, job from emp where sal>=(select min(sal) from emp) && job like 'M%'